name: Unit Tests

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show environment
        run: |
          echo "Running on:"
          hostname
          echo "Python:"
          python3 --version

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt

      - name: Run unit tests
        run: |
          ./run_tests.sh
